<div class="row">
    <div class="span9">
        <table class="table">
            <tr>
                <td colspan="8">
                    <div class="btn-group" style="vertical-align:bottom;">
                        <?=$this->form?>
                    </div>
                </td>
            </tr>
        </table>

        <div id="id_ajax_content">
            <div class="table">
                <table id="id_table_feedback" class="tablesorter">
                    <thead>
                    <tr>
                        <th colspan="3">Рейсів всього: <?=$this->iAllRaces?></th>
                        <th colspan="3">Зірваних рейсів: <?=$this->iFailRaces?></th>
                        <th colspan="3">Продано квитків: <?=$this->iPaidTickets?></th>
                    </tr>
                    <tr>
                        <th class="header" style="width:50px">#</th>
                        <th>Місця</th>
                        <th style="width:100px">Прийнято</th>
                        <th style="width:100px">Відправлення</th>
                        <th style="width:100px">Прибуття</th>
                        <th>TЗ</th>
                        <th>№</th>
                        <th>Cтатус</th>
                        <th class="header" style="width:250px">маршрут</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody><?=$this->partialLoop('routes/items/raceout.phtml', $this->list)?></tbody>
                </table>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <script>


    </script>