<h3><?=$this->sTitle?></h3>
<div class="row">
    <div class="span9">
        <table class="table">
            <tr>
                <td colspan="8">
                    <div class="btn-group" style="vertical-align:bottom;">
                        <?=$this->formRoute?>
                        <div class="btn-group" style="vertical-align:bottom;">
                            <a id="id_edit_item_0" class="btn btn-primary edit" href="#myModal" role="button" data-toggle="modal" >Додати новый рейс маршруту</a>
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <div id="id_ajax_content">
            <div class="table">
                    <table id="id_table_feedback" class="tablesorter">
                    <thead>
                    <tr>
                        <th id="id_sort_id" class="header" style="width:50px">#</th>
                        <th id="id_sort_year" class="header" style="width:50px">Рік</th>
                        <th id="id_sort_month" class="header" style="width:70px">Місяць</th>
                        <th id="id_sort_day" class="header" style="width:50px">День</th>
                        <th id="id_sort_hour" class="header" style="width:50px">Годин</th>
                        <th id="id_sort_minutes" class="header" style="width:70px">Хвилин</th>
                        <th id="id_sort_reserv" class="header" style="width:70px">Резерв</th>
                        <th></th>
                    </tr>
                    </thead>
                    <?
                    if(!empty($this->aSchedule)) {
                        ?><tbody><?= $this->partialLoop('partials/schedules.phtml', $this->aSchedule) ?></tbody><?
                     }?>
                    </table>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>