<div class="row">
    <div class="span9">
        <div class="form iniline"><?=$this->form?></div>
        <?/* div id="id_row_9">
            N4 - Маршрут 4 тест Одеса-Зеленопілля Автобус Новоплан 42 місць
            <a id="id_tickets_9" class="btn btn-mini edit" href="#myModal" role="button" data-toggle="modal" title="квитки" alt="квитки"><i class="icon-eye-open"></i></a>
         </div */?>
        <div>
            <a id="id_points" class="btn btn-mini edit" href="#myModal" role="button" data-toggle="modal" title="Автостанція" alt="Автостанція"><i class="icon-eye-open"></i></a>
        </div>

        <div id="id_ajax_content">

        </div>
    </div>
</div>