<h2>Автоматизована Система Керування</h2>
<h2>Автобусними Перевезеннями</h2>
<br />
&nbsp;
&nbsp;
<h4>Загальний стан системи</h4>
<table>
    <tr><td> &nbsp; </td></tr>
    <tr><td>ZF version</td>
        <td><?=Zend_Version::VERSION?></td>
    </tr>
    <tr><td> &nbsp; </td></tr>
    <tr>
        <td>Статус Cистеми</td>
        <td>OK</td>
    </tr>
    <tr><td>Статус БД</td>
        <td>OK</td>
    </tr>
    <tr>
        <td>Статус АРМ</td>
        <td>OK</td>
    </tr>
    <tr><td> &nbsp; </td></tr>
    <tr>
        <td>Кількість користувачів онлайн</td>
        <td> 12 </td>
    <tr>
        <td>Кількість сессій</td>
        <td> 5 </td>
    </tr>
</table>
<? /* input type="button" name="test" onclick="test();" value="Саша тыцни сюда" />
<script>
    function test()
    {
        $.post("http://localhost/index.php", {print: 1, mssg: 'test'}, function(answ){
            console.log(answ);
        }, 'json').fail(function () {
            console.log("error");
        });
    }


</script */?>

