<div class="contentItem first">
    <div class="contentTop"></div>
    <div class="contentBody">
	<div class="title">
                <div class="title">
                    <div class="error"><?=$this->errMessage?></div>
                    <?=$this->form?>   
		</div>
		<div class="description"></div>	       
	</div>
    <div class="clearfix"></div>
    </div>
    <div class="contentBottom"></div>
</div>
		
			
		
		