<div class="contentItem first">
    <div class="contentTop"></div>
    <div class="contentBody">
        <div class="title">
            <div class="title">
                <form method="post" action="/index/time">
                <input type="text" name="dt" value="<?=$this->request?>"/>
                <br/><?=$this->answer?><br/>
                <input type="submit">
                </form>
            </div>
            <div class="description"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="contentBottom"></div>
</div>