<style>H2 {font: bold 16px Verdana;}TH {font: bold 11px Verdana;}TD {font: 10px Verdana;}table.STYLE tr TH {font: bold 11px Verdana;border:solid windowtext .5pt;}table.STYLE tr TD {font: 10px Verdana;border: 1px solid windowtext .5pt;}B {font: bold 10px Verdana;}.STYLE{ border-collapse:collapse;border: 1px solid windowtext .5pt;}</style>
<?/* style="font-family:Courier New;font-size:9.8"*/?>
<h1>Реестр відомостей</h1>

<h3>Об'єкт(и) - <?=$this->station->title."\n"?></h3>

Звіт створено	<?=date("d.m.Y H:i")."\n"?><br/>
Період	<?=$this->dtb?> - <?=$this->dte."\n"?><br/>
Оператор:	<?=$this->oSession->login."\n"?><br/>
<table border="1" class="STYLE">
<tr align="center">
    <th>Код</th>
    <th>Перевізник</th>
    <th>#</th>
    <th>Проїзд</th>
    <th>Тариф</th>
    <th>Тар. орг.</th>
    <th>Cтр. С.</th>
    <th>К расч.</th>
    <th>Билетів</th>
    <th>Багажа</th>
    <th>Пос.</th>
</tr>
<?=$this->partialLoop('reports/items/printlistitem.phtml', $this->rs)?>
    <tr align="left">
        <th colspan="3">Всього:</th>
        <th  align="right"><?=sprintf("%8.2f",$this->partialLoop()->view->total1)?></th>
        <th  align="right"><?=sprintf("%8.2f",$this->partialLoop()->view->total2)?></th>
        <th  align="right"><?=sprintf("%8.2f",$this->partialLoop()->view->total3)?></th>
        <th  align="right"><?=sprintf("%8.2f",$this->partialLoop()->view->total4)?></th>
        <th  align="right"><?=sprintf("%8.2f",$this->partialLoop()->view->total5)?></th>
        <th  align="right"><?=sprintf("%8d",$this->partialLoop()->view->totalplaces)?></th>
        <th  align="right"><?=sprintf("%8d",$this->partialLoop()->view->totalluggage)?></th>
        <th  align="right"><?=sprintf("%8.2f",0)?></th>
    </tr>




</table>
</pre>