<?
if($this->partialLoop()->view->conv_code!=$this->conv_code){
    if($this->partialLoop()->view->conv_code!='') {?>
        <td colspan="2" align="left">Всього:</td>
        <td><?=sprintf("%8.2f",$this->partialLoop()->view->total1)?></td><? /*по відомості*/?>
        <td><?=sprintf("%8.2f",$this->partialLoop()->view->total2)?></td><? /*Тар. пер.*/ ?>
        <td><?=sprintf("%8.2f",$this->partialLoop()->view->total3)?></td><? /*Тар. орг.*/ ?>
        <td><?=sprintf("%8.2f",$this->partialLoop()->view->total4)?></td><? /*Cтрах. Сбір*/ ?>
        <td><?=sprintf("%8.2f",$this->partialLoop()->view->total5)?></td><? /*Cтан. Сбір.*/ ?>
        <td><?=sprintf("%8.2f",$this->partialLoop()->view->total6)?></td><? /*Ком. всього*/ ?>
        <td><?=sprintf("%8.2f",$this->partialLoop()->view->total1+$this->partialLoop()->view->total4+$this->partialLoop()->view->total5+$this->partialLoop()->view->total6)?></td><? /*Готівка*/ ?>
        <td><?=sprintf("%3d",$this->partialLoop()->view->totalplaces)?></td><?/*Чеків*/?>
        <td><?=sprintf("%8.2f",$this->partialLoop()->view->total7)?></td><?/*ПДВ орг.*/?>
    <?


        $this->partialLoop()->view->totalplaces = 0;
        $this->partialLoop()->view->total1 = 0.0;
        $this->partialLoop()->view->total2 = 0.0;
        $this->partialLoop()->view->total3 = 0.0;
        $this->partialLoop()->view->total4 = 0.0;
        $this->partialLoop()->view->total5 = 0.0;
        $this->partialLoop()->view->total6 = 0.0;
        $this->partialLoop()->view->total7 = 0.0;
    }
    ?>
    <tr align="left">
    <th colspan="10"><?=$this->conv_code."-".$this->conv_title?></th>
    </tr><?
    $this->partialLoop()->view->conv_code=$this->conv_code;
}
?>
<tr align="right">
    <td><?=$this->code?></td>
    <td><?=date("d.m.Y",strtotime($this->dt_time_begin))?></td><? /*Дата відправлення*/?>
    <td><?=sprintf("%8.2f",$this->col1)?></td><? /*по відомості*/?>
    <td><?=sprintf("%8.2f",$this->col2)?></td><? /*Тар. пер.*/ ?>
    <td><?=sprintf("%8.2f",$this->col3)?></td><? /*Тар. орг.*/ ?>
    <td><?=sprintf("%8.2f",$this->col4)?></td><? /*Cтрах. Сбір*/ ?>
    <td><?=sprintf("%8.2f",$this->col5)?></td><? /*Cтан. Сбір.*/ ?>
    <td><?=sprintf("%8.2f",$this->col6)?></td><? /*Ком. всього*/ ?>
    <td><?=sprintf("%8.2f",$this->col1+$this->col4+$this->col5+$this->col6)?></td><? /*Готівка*/ ?>
    <td><?=sprintf("%3d",$this->places)?></td><?/*Чеків*/?>
    <td><?=sprintf("%8.2f",$this->col7)?></td><?/*ПДВ орг.*/?>

</tr>
<?
$this->partialLoop()->view->totalplaces+=(int)$this->places;
$this->partialLoop()->view->total1+=(float)$this->col1;
$this->partialLoop()->view->total2+=(float)$this->col2;
$this->partialLoop()->view->total3+=(float)$this->col3;
$this->partialLoop()->view->total4+=(float)$this->col4;
$this->partialLoop()->view->total5+=(float)$this->col5;
$this->partialLoop()->view->total6+=(float)$this->col6;
$this->partialLoop()->view->total7+=(float)$this->col7;

$this->partialLoop()->view->atotalplaces += (int)$this->places;
$this->partialLoop()->view->atotal1 += (float)$this->col1;
$this->partialLoop()->view->atotal2 += (float)$this->col2;
$this->partialLoop()->view->atotal3 += (float)$this->col3;
$this->partialLoop()->view->atotal4 += (float)$this->col4;
$this->partialLoop()->view->atotal5 += (float)$this->col5;
$this->partialLoop()->view->atotal6 += (float)$this->col6;
$this->partialLoop()->view->atotal7 += (float)$this->col7;


