<tr id="id_item_<?=$this->id?>_0_<?=$this->type?>">
    <td><?=$this->id?></td>
    <td><b><small><?php echo $this->title ?></small></b></td>
    <td><?=sprintf("%d",$this->description)?></td>
    <td class="actions">
       <div class="btn-group">
            <a id="id_edit_item_<?=$this->id?>_0_<?=$this->type?>" class="btn btn-mini edit" href="#myModal" role="button" data-toggle="modal"><i class="icon-pencil"></i></a>
            <a id="id_del_item_<?=$this->id?>_0_<?=$this->type?>" class="btn btn-mini delete" href="javascript:void(0);"><i class="icon-remove"></i></a>
        </div>
    </td>
</tr>