<?php 
if($this->sMssg) {?><div class="alert alert-success fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sMssg?><br /></div><?php }
if($this->sError){?><div class="alert alert-error fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sError?><br /></div><?php  }
?><div class="well">
	<?=$this->formcategory?>
	<div class="clearfix"></div>
</div>

<table id="id_table_cat" class="table tablesorter">
    <thead>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?=$this->partialLoop('partials4adm/categories.phtml', $this->cats)?>
    </tbody>
</table>
<script>reload();
    $(document).ready(function(){
        $('#id_table_cat').tablesorter({headers: { 1: { sorter: false} }});
    });
	$('.required').tooltip({title: 'this field is required'});
</script>
