<?php 
if($this->sMssg) {?><div class="alert alert-success fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sMssg?><br /></div><?php }
if($this->sError){?><div class="alert alert-error fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sError?><br /></div><?php  }
?>
<?=$this->form?><script>
if($(".alert")) $(".alert").alert();       
$('#idCloneTmpl').submit(function(){
    loadContent($('#idCloneTmpl').attr('action'),$('#idCloneTmpl').serialize()+"&csrf_token="+govsource.Utils.getCsrfToken(),'#id_form','html');
    return false;
});
<?=$this->updJSScript?>
</script>