<div class="row">
	<div class="span9">
		<table class="table">
                        <tr>
                                <td><div class="btn-group"> 
                                        <a id="id_edit_0" class="btn btn-primary edit" href="#myModal" role="button" data-toggle="modal" >New Template</a>
                                    </div></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td style="width:90px"></td>
                       </tr>
            </table>
        <table id="id_table_mails" class="table tablesorter">
            <thead>
                <tr>
                    <th></th>
                    <th>Template name</th>
                    <th>Subject</th>
                    <th style="width:90px"></th>
                </tr>
            </thead>
            <tbody>
			    <?=$this->partialLoop('partials4adm/mails.phtml', $this->aMails)?>
            </tbody>
		</table>		
	</div>
</div>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>
   <div class="modal-body">
	  <div id="id_form">
	  </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <!-- button class="btn btn-primary">Save changes</button -->
  </div>
</div><script>reload();</script>
<script type='text/javascript'>
    $(document).ready(function(){
        $('#id_table_mails').tablesorter({headers: { 3: { sorter: false} }});
    });
</script>