<div class="row">
	<div class="span9">
		<table class="table">
            <tr>
                <td colspan="8">
                    <div class="btn-group" style="vertical-align:bottom;">
                        <a id="id_edit_event_0" class="btn btn-primary edit" href="#myModal" role="button" data-toggle="modal" >New Event</a>
                        <a id="id_edit_template_0" class="btn btn-primary edit" href="#myModal" role="button" data-toggle="modal" >New Template</a>
                        <a id="id_clone_template" class="btn btn-primary edit" href="#myModal" role="button" data-toggle="modal" >Clone Template</a>
                    </div>
                    <div class="filters-box">
                        <div class="filter-item">
                            <label for="process-filter">Process Filter</label>
                            <select class="input-medium" id="process-filter" onchange="setfilter();">
                                <option value=0>all</option>
                                <? foreach ($this->afilters['process'] as $key => $value) {
                                   echo '<option '.($this->selected_filters['process']===$value?"selected":"").' value="'.$key.'">'.$value.'</option>';
                               }?>
                            </select>
                        </div>
                    <? /*    <div class="filter-item">
                            <label for="type-filter">Type Filter</label>
                            <select class="input-medium" id="type-filter" onchange="setfilter();">
                                <option value=0>all</option>
                                <?  foreach ($this->afilters['type'] as $key => $value) {
                                   echo '<option '.($this->selected_filters['type']===$value?"selected":"").' value="'.$key.'">'.$value.'</option>';
                               }?>
                            </select>
                        </div> */ ?>
                    </div>
                </td>
            </tr>
        </table>
        <table id="id_table_mailsadv" class="table table-hover tablesorter">
            <thead>
            <tr>
                <th>ID</th>
                <th>Event</th>
                <th>Process</th>
            <?//    <th>Type</th> ?>
                <th>Customer Email</th>
                <th>Contractor Email</th>
                <th>Assurer Email</th>
                <th>Staff<br> Email</th>
                <th>Team<br> Email</th>
                <th>Admin<br> Email</th>
                <th>All<br> Email</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
			    <?=$this->partialLoop('partials4adm/mailsadv.phtml', $this->aEvents)?>
            </tbody>
		</table>		
	</div>
</div>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>
   <div class="modal-body">
	  <div id="id_form">
	  </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <!-- button class="btn btn-primary">Save changes</button -->
  </div>
</div><script>reload();</script>
<script type='text/javascript'>
    $(document).ready(function(){
        $('#id_table_mailsadv').tablesorter({headers: { 10: { sorter: false} }});
    });
</script>