<?php 
if($this->sMssg) {?><div class="alert alert-success fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sMssg?><br /></div><?php }
if($this->sError){?><div class="alert alert-error fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sError?><br /></div><?php  }
?><div class="well">
	<input type="file" /><input type="submit" class="btn btn-primary" value="Upload" />
	<div class="clearfix"></div>
</div>

<table class="table table-striped media">
<tr>
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr><tr >
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr><tr >
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr><tr >
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr><tr >
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr><tr >
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr><tr >
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr><tr >
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr><tr >
    <td><img src="<?=CDN_URL?>/img/none.jpg"></td>
    <td>/img/none.jpg</td>
    <td style="width:90px;">
      	<div class="btn-group">
		    <a id="id_del_<?=$this->id?>" class="btn delete" href="#" title="delete <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-remove"></i></a>
		    <a class="btn" href="/admin/index/cat/<?=$this->id?>/" title="pages in <?=htmlspecialchars($this->name_menu,ENT_QUOTES)?>"><i class="icon-eye-open"></i></a>
    	</div>
    </td>
  </tr>
</table>
<div class="pagination pagination-centered">
  <ul>
    <li class="disabled"><a href="#">«</a></li>
    <li class="active"><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">»</a></li>
 </ul>
</div>
<script>	
	$('.required').tooltip({title: 'this field is required'});
</script>
