<div class="row">
	<div class="span9">
		<table class="table">
                    <tr><td rowspan="2">Project id</td><td colspan="5">Contractor</td><td colspan="5" >Assurer</td><td rowspan="2">Amazon</td><td rowspan="2"></td></tr>
                    <tr><td>rate</td><td>markup($)< rate</td><td>markup(%) < rate</td><td>markup($)</td><td>markup(%)</td><td>rate</td><td>markup($) < rate</td><td>markup(%) < rate</td><td>markup($)</td><td>markup(%)</td></tr>
			<?=$this->partialLoop('partials4adm/price.phtml', $this->pricelist)?>	
		</table>		
	</div>
</div>
