<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Admin - Gosource - <?=$this->sTitle?></title>
	<meta name="author" content="developers v0id inlisu.com 2012"/>
        <link rel="shortcut icon" href="/favicon.ico" />
	<meta name="viewport" content="width=device-width,initial-scale=1"/>
    <link rel="stylesheet" href="<?=CDN_URL?>/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?=CDN_URL?>/css/admin.css"/>
	<script src="<?=CDN_URL?>/js/libs/modernizr-2.0.6.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <?=$this->jsLinks?>
	<script src="<?=CDN_URL?>/js/libs/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="page-header"><a href="/admin/projscroll" class="btn"><i class="icon-chevron-left"></i>Go back</a> <h2><?=$this->sTitle?></h2></div>
            </div>
        </div>

        <div class="row">
	        <div class="span12">
	            <div class="content" id="ID_content"><?php
	                if($this->sMssg) {?><div class="alert alert-success fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sMssg?><br /></div><?php }
	                if($this->sError){?><div class="alert alert-error fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sError?><br /></div><?php  }
	                ?>

	                <?=$this->form?>
	                <div class="clearfix"></div>
	            </div>
	        </div>
        </div>

        <!-- End of .container -->
    </div>
    <!--[if lt IE 7 ]>
	<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
	<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
    <div id="loader" class="loader"><div><img src="<?=CDN_URL?>/img/loader.gif" alt="" /></div></div>
</body>
</html>