<?if($this->sError || $this->sMssg){?>
<div class="alert alert-<?=$this->sError?'error':'success'?> fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sError .' '. $this->sMssg?><br /></div>
<?}?>
<div class="row">
	<div class="span9">
		<table class="table">
            <tr>
                <td colspan="3">
                    <div class="btn-group">
                        <a id="id_edit_option_0" class="btn btn-primary edit" href="#myModal" role="button" data-toggle="modal" >New Option</a>
                    </div>
                </td>
            </tr>
            <tr>
                <td><b>Option</b></td>
                <td><b>Value</b></td>
                <td><b>Source</b></td>
                <td></td>
                <td></td>
            </tr>
			<?=$this->partialLoop('partials4adm/systemsettings.phtml', $this->aOptions)?>
		</table>
	</div>
</div>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>
   <div class="modal-body">
	  <div id="id_form">
	  </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <!-- button class="btn btn-primary">Save changes</button -->
  </div>
</div>
<script>reload();</script>