<div class="row">
	<div class="span9">
		<table class="table">
                        <tr>
                                <th colspan="3"><div class="btn-group"> 
                                        <a id="id_edit_0" class="btn btn-primary edit" href="#myModal" role="button" data-toggle="modal" >New Technology</a>
                                    </div></th>
                                <th></th>
                                <th></th>
                                <th style="width:90px"></th>
                       </tr>
            </table>
        <table id="id_table_technologies" class="table tablesorter">
            <thead>
                <tr>
                    <th>#</th>
                    <th></th>
                    <th>Name</th>
                    <th>Contractors</th>
                    <th>Weight</th>
                    <th style="width:90px"></th>
                </tr>
            </thead>
            <tbody>
			    <?=$this->partialLoop('partials4adm/technologies.phtml', $this->aTechno)?>
            </tbody>
		</table>		
	</div>
</div>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>
   <div class="modal-body">
	  <div id="id_form">
	  </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <!-- button class="btn btn-primary">Save changes</button -->
  </div>
</div><script>reload();</script>
<script type='text/javascript'>
    $(document).ready(function(){
        $('#id_table_technologies').tablesorter({headers: { 1: { sorter: false},5: { sorter: false} }});
    });
</script>