<?php 
if($this->sMssg) {?><div class="alert alert-success fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sMssg?><br /></div><?php }
if($this->sError){?><div class="alert alert-error fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sError?><br /></div><?php  }
?>
<?=$this->form?><script>
if($(".alert")) $(".alert").alert();       
$('#idSendTehno').submit(function(){
    loadContent($('#idSendTehno').attr('action'),$('#idSendTehno').serialize(),'#id_form','html');
    return false;
});
$('#myModal').on('hidden', function () {
    document.location.reload();
});
</script>