<?php
if(!$this->isAjax){
if($this->sMssg) {?><div class="alert alert-success fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sMssg?><br /></div><?php }
if($this->sError){?><div class="alert alert-error fade in"><button type="button" class="close" data-dismiss="alert">×</button><?=$this->sError?><br /></div><?php  }
?>
<input type="hidden" class="myfilter" name="sort" value=""/>
<input type="hidden" class="myfilter" name="order" value=""/>
<div id="id_ajax_content"><? } ?>
<div class="row">
	<div class="span9">
		<table class="table tablesorter">
            <thead>
            <tr>
                <th id="id_sort_login" class="header">Login / E-mail</th>
                <th id="id_sort_fname" class="header">First Name</th>
                <th id="id_sort_sname" class="header">Last Name</th>
                <th id="id_sort_phone" class="header">Phone number</th>
                <th style="width:90px"></th>
            </tr>
            </thead>
            <tbody>
			<?=$this->partialLoop('partials4adm/users.phtml', $this->aUsers)?>
            </tbody>
		</table>
	</div>
</div>
<script>var jSearchData=<?=$this->aFilter?>;</script>
<div class="pagination">
<ul>
<?php
    if(!empty($this->aUsers)){
           if($this->page>1){?><li><a href="/admin/users/page/<?=$this->page-1?>/<?=$this->filters?>" class="prev a_paginator">&laquo;</a></li><? } ?>
           <?php
           $k=5;
           $iStart=$this->page-5;
           if($iStart>$this->iPages) $iStart=$iPages-10;
           if($iStart<1)       $iStart=1;
           $iter=0;
           while($iter<10){
              ?><li class="<?=($iStart==$this->page) ? ' active' : ''?>"><a class="a_paginator" href="/admin/users/page/<?=$iStart?>/<?=$this->filters?>"><?=$iStart?></a></li><?
              $iter++;
              $iStart++;
              if($iStart>$this->iPages) break;
           }
           ?><?php if($this->page<$this->iPages){?><li><a href="/admin/users/page/<?=$this->page+1?>/<?=$this->filters?>" class="next a_paginator">&raquo;</a></li><? }
   }?>
<ul>
</div>
<?//=$this->paginationControl($this->paginator)?>
<div class="clearfix"></div>
<?php if(!$this->isAjax){?></div>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>
  <div class="modal-body">
	  <div id="id_form"></div>
      <div class="clearfix"></div>

        <p class="text-error" id="id_error">
        </p>        
              
        <p class="text-success" id="id_loading">
        </p>

  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button id="id_submit" class="btn btn-primary">Save changes</button>
  </div>
</div>
<? } else{?><script>reload();</script><?} ?>
<script>
    $(document).ready(function(){
        // highlight table headers
        if(jSearchData.sort.length>0){
            if(jSearchData.order.length>0){
                $('#id_sort_'+jSearchData.sort).addClass('headerSort'+(jSearchData.order=='desc'?'Up':'Down'));
            }
        }
        // update table headers
        $('.tablesorter .header').on('click',function(){
            var order = 'asc';
            var sort = $(this).attr('id').split('_')[2];

            if($(this).hasClass('headerSortUp')){
                $(this).removeClass('headerSortUp').addClass('headerSortDown');
                order = 'asc';
            } else if($(this).hasClass('headerSortDown')){
                $(this).removeClass('headerSortDown').addClass('headerSortUp');
                order = 'desc';
            } else {
                $(this).addClass('headerSortDown');
            }
            $('.myfilter[name="sort"]').val(sort);
            $('.myfilter[name="order"]').val(order);

            var data = {};
            $('.myfilter').each(function(){data[$(this).attr('name')]=$(this).val();});
            data['csrf_token'] = govsource.Utils.getCsrfToken();
            loadContent('/admin/users/',data,'#id_ajax_content','html');
            return false;
        });
        $('.a_paginator').click(function(){
            jSearchData['csrf_token'] = govsource.Utils.getCsrfToken();
            loadContent($(this).attr('href'),jSearchData,'#id_ajax_content','html');
            return false;
        });

    });
</script>
