<div class="search_home">
		<div>
			<hgroup>
				<h1>Get your job <b>done</b>.</h1>
				<h2>Find the right people, the right team and some really nice text here</h2>
			</hgroup>
			<div class="input"><form onsubmit="return search();">
				<input id="IDkwd" type="text" placeholder="Contractor Search"/>
				<div class="dropdown">
					<p id="IDpart" class="active">Contractor</p>
					<div id="IDlist" class="list">
						<p>Contractor</p>
						<p>Templates</p>
						<p>Platforms</p>
						<p>Assurers</p>
					</div>
				</div>
				<input type="submit" value="Search"/>
                                </form>
				<div class="clearfix"></div>	
			</div>
			<a href="/project/start/" class="launch">Launch project</a>
		</div>
        </div>		
	<div class="container">
                <?=$this->content?>		
	</div>
