<h3><?=$this->sTitle?></h3>
<div class="row">
    <div class="span9">
        <table class="table">
            <tr>
                <td colspan="8">
                    <div class="btn-group" style="vertical-align:bottom;">
                        <a id="id_edit_item_0" class="btn btn-primary edit" href="#myModal" role="button" data-toggle="modal" >Додати нову юр.особу</a>
                    </div>
                </td>
            </tr>
        </table>
        <div class="well">
    <? /*div class="filter projects">
        <span> Filter By: </span>
        <select name="status" class="myfilter">
            <option value="">Feedback Status</option>
            <option value="good">Good</option>
            <option value="normal">Normal</option>
            <option value="bad">Bad</option>
        </select><a href="javascript:void(0);" id="id_apply_filter" class="btn">Apply</a>
        <input type="hidden" class="myfilter" name="sort" value=""/>
        <input type="hidden" class="myfilter" name="order" value=""/>
    </div */?>
</div>
<div id="id_ajax_content">
    <div class="table">
        <table id="id_table_feedback" class="tablesorter">
            <thead>
            <tr>
                <th id="id_sort_id" class="header" style="width:25px">#</th>
                <th id="id_sort_rate" class="header" style="width:300px">Назва</th>
                <th id="id_sort_date" class="header" style="width:100px">Тип</th>
                <th style="width:150px">Юр.адреса</th>
                <th style="width:150px">Адреса офісу</th>
                <th></th>
            </tr>
            </thead>
            <tbody><?=$this->partialLoop('partials/organizations.phtml', $this->paginator)?></tbody>
        </table>
    </div>
    <script>var jSearchData=<?=$this->aFilter?>;</script>
    <?=$this->paginationControl($this->paginator)?>
    <div class="clearfix"></div>
   </div>
 </div>

<? /* script>
    $(document).ready(function(){
        // highlight table headers
        if(jSearchData.sort.length>0){
            if(jSearchData.order.length>0){
                $('#id_sort_'+jSearchData.sort).addClass('headerSort'+(jSearchData.order=='desc'?'Up':'Down'));
            }
        }
        // update table headers
        $('.tablesorter .header').on('click',function(){
            var order = 'asc';
            var sort = $(this).attr('id').split('_')[2];

            if($(this).hasClass('headerSortUp')){
                $(this).removeClass('headerSortUp').addClass('headerSortDown');
                order = 'asc';
            } else if($(this).hasClass('headerSortDown')){
                $(this).removeClass('headerSortDown').addClass('headerSortUp');
                order = 'desc';
            } else {
                $(this).addClass('headerSortDown');
            }
            $('.myfilter[name="sort"]').val(sort);
            $('.myfilter[name="order"]').val(order);

            var data = {};
            $('.myfilter').each(function(){data[$(this).attr('name')]=$(this).val();});
            loadContent('/admin/feedbacks/',data,'#id_ajax_content','html');
            return false;
        });
    });
</script */?>