<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>APM BusTickets - <?= $this->sTitle ?></title>
        <meta name="author" content="developers v0id inlisu.com 2014"/>
        <!-- link rel="shortcut icon" href="/favicon.ico" / -->
        <meta name="csrf_token" content="<? /*=$this->GetToken(1)->csrf_token->getSession()->hash */?>"/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bustickets.css"/>
        <?=$this->headLink()?>
    </head>
    <body>

        <div class="container admin">
            <div class="row">
                <div class="span12">
                    <div class="page-header">
                        <h2><?= $this->sTitle ?></h2>
                    </div>
                   <div class="menu-kassa"> <?=$this->navigation()->menu($this->menu)->setPartial('partials/menu.phtml')?></div>
                </div>
            </div>
            <div class="row">
                <div class="span9">
                    <div class="content" id="ID_content">
                        <!-- BEGIN container -->
                        <?= $this->layout()->content ?>
                        <!-- End container -->
                        <div class="clearfix"></div>	
                    </div>

                </div>				
            </div>
        </div>
        <!-- Modal -->
        <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div id="id_form"></div>
                <div id="id_form_load"></div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="id_btn_save">Записати</button>
                <button class="btn" id="id_btn_del" >Видалити</button>
                <button class="btn" data-dismiss="modal" aria-hidden="true">Відміна</button>
            </div>
        </div>
        <div id="loader" class="loader"><div><img src="/img/loader.gif" alt="" /></div></div>
        <script src="/js/libs/jquery-1.7.1.min.js"></script>
        <script src="/js/libs/bootstrap.min.js"></script>
        <script src="/js/global/index.js"></script>
        <script src="/js/global/utils.js"></script>
        <script src="/js/libs/tablesorter/jquery.tablesorter.min.js"></script>
        <?=$this->headScript()?>
    </body>
</html>