<!doctype html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>APM BusTickets - Авторизація</title>
	<meta name="author" content="developers v0id inlisu.com 2013"/>
        <!--link rel="shortcut icon" href="/favicon.ico" / -->
	<meta name="viewport" content="width=device-width,initial-scale=1"/>
    <link rel="stylesheet" href="/css/bootstrap.min.css">

</head>
<body>    
	<div class="container adminfront">
		<header>
			<div class="row">
				<div class="span16">
					<h2>Авторизація</h2>
				</div>
                                
			</div>

		</header>		
				
		<div class="content" id="ID_content">			
			<?=$this->layout()->content?>		
            <div class="clearfix"></div>
        </div> <!-- End of .container -->
</div>
</body>
</html>