<?php

$html = array('<ul class="nav nav-tabs nav-stacked">');

/** @var Zend_Navigation_Page $page */
foreach ($this->container as $page) {
    // show only the current branch and the visible item
    if (!$page->isVisible()
        || ($this->menu()->getOnlyActiveBranch() && !$page->isActive(true))) {
        continue;
    }

    // header
    if ($page->getHref()) $html[] = '<li class="'.($page->isActive() ? 'active' : '') . '"><a href="' . $page->getHref() . '">';
    elseif (!empty($page->pages)) $html[] = '<li class="'.($page->isActive(1) ? 'active' : '') . ' dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">';
    else $html[] = '<li class="nav-header">';
    $html[] = $page->getLabel();
    if ($page->getHref()) $html[] = '</a>';
    elseif (!empty($page->pages)) $html[] = ' <b class="caret"></b></a>';

    if (!empty($page->pages)) {
        $html[] = '<ul class="dropdown-menu">';
        /** @var Zend_Navigation_Page $subpage */
        foreach ($page->pages as $subpage) {
            // visibility of the sub-page
            if (!$subpage->isVisible()) {
                continue;
            }
            if ($subpage->getLabel() == 'divider') {
                $html[] = '<li class="divider"></li>';
                continue;
            }

            if (!$subpage->getHref()) {
                $html[] = '<li class="nav-header">';
                $html[] = $subpage->getLabel();
                $html[] = '</li>';
                continue;
            }

            $html[] = '<li' . ($subpage->isActive() ? ' class="active"' : '') . '>';
            $html[] = '<a href="' . $subpage->getHref() . '">';

            if ($subpage->get('icon')) {
                $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
            }

            $html[] = $subpage->getLabel();
            $html[] = "</a>";
            $html[] = "</li>";
        }
        $html[] = '</ul>';
    }
    $html[] = "</li>";
}

$html[] = '</ul>';

echo join(PHP_EOL, $html);